services:
  - type: web
    name: system-onco-ml-api
    runtime: docker
    plan: 2c-4g
    region: singapore
    dockerfilePath: ./system-onco/ml-pipeline/Dockerfile
    dockerContext: ./system-onco/ml-pipeline
    healthCheckPath: /health
    envVars:
      - key: CORS_ORIGINS
        value: https://system-onco-neuro-cnn.vercel.app
